/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ant-man.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-30-ant-ant-man-e592122f0e0741479efdb90810726d97
Title: Disney Infinity 3.0 - ANT Ant-Man
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function AntMan(props) {
  const { nodes, materials } = useGLTF('./models/ant-man.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.83}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes['ANT_Ant-Man_LOD_0_ANT_Ant-Man_0'].geometry} scale={100} >
            <DissolveMaterial
              baseMaterial={materials['ANT_Ant-Man']}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#6f0b0b"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/ant-man.glb')
