/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/black_panther.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-30-avg-black-panther-b124d719ad844876b8744c818d846847
Title: Disney Infinity 3.0 - AVG Black Panther
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function BlackPanther(props) {
  const { nodes, materials } = useGLTF('./models/black_panther.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.88}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh
            geometry={nodes.AVG_Black_Panther_Body_AVG_Black_Panther_0.geometry}
            scale={100}
          >
            <DissolveMaterial
              baseMaterial={materials.AVG_Black_Panther}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#452d8b"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/black_panther.glb')
