/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/spider-man.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-20-spd-spider-man-e00cdb09c5614635ab720352edc94bd5
Title: Disney Infinity 2.0 - SPD Spider-Man
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function SpiderMan(props) {
  const { nodes, materials } = useGLTF('./models/spider-man.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.87}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes.SPD_Spider_Man_SPD_Spider_Man_0.geometry} rotation={[-Math.PI / 2, 0, 0]} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.SPD_Spider_Man}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#1422ab"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/spider-man.glb')
