/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/vision.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-30-avg-vision-ca6237b73ab04a2c9a798c2620925ad9
Title: Disney Infinity 3.0 - AVG Vision
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function Vision(props) {
  const { nodes, materials } = useGLTF('./models/vision.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.88}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes.AVG_Vision_Cape_AVG_Vision_Cape_0.geometry} scale={100}>
            <DissolveMaterial
              baseMaterial={materials.AVG_Vision_Cape}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#342b00"
            />
          </mesh>
          <mesh geometry={nodes.AVG_Vision_Eyes_AVG_Vision_Eyes_0.geometry} scale={100}>
            <DissolveMaterial
              baseMaterial={materials.AVG_Vision_Eyes}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#342b00"
            />
          </mesh>
          <mesh geometry={nodes.AVG_Vision_Body_AVG_Vision_Body_0.geometry}  scale={100}>
            <DissolveMaterial
              baseMaterial={materials.AVG_Vision_Body}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#342b00"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/vision.glb')
