/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/winter_soldier.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-20-avg-winter-soldier-bf5a62079015486dad97cabae0575cce
Title: Disney Infinity 2.0 - AVG Winter Soldier
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function Bucky(props) {
  const { nodes, materials } = useGLTF('./models/winter_soldier.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0.5, 0]} scale={0.01}>
        <mesh geometry={nodes.AVG_Winter_Soldier_Body_AVG_Winter_Soldier_Body_0.geometry} scale={100}>
          <DissolveMaterial
            baseMaterial={materials.AVG_Winter_Soldier_Body}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            color="#1f2a64"
          />
        </mesh>
        <mesh geometry={nodes.AVG_Winter_Soldier_Eyes_AVG_Winter_Soldier_Eyes_0.geometry} scale={100} >
          <DissolveMaterial
            baseMaterial={materials.AVG_Winter_Soldier_Eyes}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            color="#1f2a64"
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/winter_soldier.glb')
