/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/captain_america.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/di-30-avg-captain-america-the-first-avenger-34a2b01487bd446d94375e6088a65f1f
Title: DI 3.0 - AVG Captain America The First Avenger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function Capsy(props) {
  const { nodes, materials } = useGLTF('./models/captain_america.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.87}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes.AVG_Captain_America_The_First_Avenger_Eyes_AVG_Captain_America_The_First_Avenger_Eyes_0.geometry} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Captain_America_The_First_Avenger_Eyes}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#00334a"
            />
          </mesh>
          <mesh geometry={nodes.AVG_Captain_America_The_First_Avenger_Body_AVG_Captain_America_The_First_Avenger_Body_0.geometry} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Captain_America_The_First_Avenger_Body}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#00334a"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/captain_america.glb')
