/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/falcon.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-20-avg-falcon-movie-8eb55029a9cb4d8bbc653aa008bc4473
Title: Disney Infinity 2.0 - AVG Falcon Movie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function Falcon(props) {
  const { nodes, materials } = useGLTF('./models/falcon.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0.5, 0]}  scale={0.01}>
        <mesh geometry={nodes.AVG_Falcon_Movie_Wings_LOD_0_AVG_Falcon_Movie_Wings_0.geometry} position={[0, 145.71, -19.12]} scale={100} >
          <DissolveMaterial
            baseMaterial={materials.AVG_Falcon_Movie_Wings}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            // color="#a0490d"
          />
        </mesh>
        <mesh geometry={nodes.AVG_Falcon_Movie_Wing_Pack_LOD_0_AVG_Falcon_Movie_Wings_0.geometry} position={[0, 145.71, -19.12]} scale={100}>
          <DissolveMaterial
            baseMaterial={materials.AVG_Falcon_Movie_Wings}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            // color="#a0490d"
          />
        </mesh>
        <mesh geometry={nodes.AVG_Falcon_Movie_Goggles_AVG_Falcon_Movie_Goggles_0.geometry} scale={100}>
          <DissolveMaterial
            baseMaterial={materials.AVG_Falcon_Movie_Goggles}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            // color="#a0490d"
          />
        </mesh>
        <mesh geometry={nodes.AVG_Falcon_Movie_Eyes_AVG_Falcon_Movie_Eyes_0.geometry} scale={100}>
          <DissolveMaterial
            baseMaterial={materials.AVG_Falcon_Movie_Eyes}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            // color="#a0490d"
          />
        </mesh>
        <mesh geometry={nodes.AVG_Falcon_Movie_Body_AVG_Falcon_Movie_Body_0.geometry} scale={100}>
          <DissolveMaterial
            baseMaterial={materials.AVG_Falcon_Movie_Body}
            visible={props.dissolveVisible}
            onFadeOut={props.onFadeOut}
            // color="#a0490d"
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/falcon.glb')
