/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/hulkbuster.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-30-avg-hulkbuster-5a66e945112b45d08a82830af2f2d918
Title: Disney Infinity 3.0 - AVG Hulkbuster
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function HulkBuster(props) {
  const { nodes, materials } = useGLTF('./models/hulkbuster.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.28}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes.AVG_Hulkbuster_Arms_LOD_0_AVG_Hulkbuster_Arms_0.geometry} rotation={[-Math.PI / 2, 0, 0]} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Hulkbuster_Arms}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#054153"
            />
          </mesh>
          <mesh geometry={nodes.AVG_Hulkbuster_Legs_LOD_0_AVG_Hulkbuster_Legs_0.geometry} rotation={[-Math.PI / 2, 0, 0]} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Hulkbuster_Legs}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#054153"
            />
          </mesh>
          <mesh geometry={nodes.AVG_Hulkbuster_Body_LOD_0_AVG_Hulkbuster_Body_0.geometry} rotation={[-Math.PI / 2, 0, 0]} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Hulkbuster_Body}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#054153"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/hulkbuster.glb')
