/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/iron_man.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-20-avg-iron-man-03c286f6542e49c0b2bff4005c899b04
Title: Disney Infinity 2.0 - AVG Iron Man
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function IronMan(props) {
  const { nodes, materials } = useGLTF('./models/iron_man.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.91}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes.AVG_Iron_Man_LOD_0_AVG_Iron_Man_0.geometry} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Iron_Man}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#a0490d"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/iron_man.glb')
