/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ultron.glb
Author: JohnLogostini (https://sketchfab.com/JohnLogostini)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/disney-infinity-30-avg-ultron-b3ab1525ca204f18a619da111a411afa
Title: Disney Infinity 3.0 - AVG Ultron
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'

export function UltronModel(props) {
  const { nodes, materials } = useGLTF('./models/ultron.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.91}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.01}>
          <mesh geometry={nodes.AVG_Ultron_LOD_0_AVG_Ultron_0.geometry} scale={100} >
            <DissolveMaterial
              baseMaterial={materials.AVG_Ultron}
              visible={props.dissolveVisible}
              onFadeOut={props.onFadeOut}
              color="#a0490d"
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/ultron.glb')
